# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 22:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balde',
            fields=[
                ('nro_balde', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('50', '50'), ('120', '120'), ('240', '240')], max_length=5)),
                ('estado', models.CharField(choices=[('En Planta', 'En Planta'), ('Ocupado', 'Ocupado')], default='En Planta', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BaldeUtilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_precinto', models.BigIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('Entrega', 'Entrega'), ('Retiro', 'Retiro')], max_length=15)),
                ('balde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Balde')),
            ],
        ),
        migrations.CreateModel(
            name='EstablecimientoGenerador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_actividad', multiselectfield.db.fields.MultiSelectField(choices=[('Hospital', 'Hospital'), ('Centro de Salud', 'Centro de Salud'), ('Clínica', 'Clínica'), ('Sanatorio', 'Sanatorio'), ('Tatuajes', 'Tatuajes'), ('Cirugia', 'Cirugia'), ('Centro Diagnóstico', 'Centro Diagnóstico'), ('Centro Vacunación', 'Centro Vacunación'), ('Consultorio Médico', 'Consultorio Médico'), ('Investigación', 'Investigación'), ('Maternidad', 'Maternidad'), ('Pediatría', 'Pediatría'), ('Laboratorio', 'Laboratorio'), ('Psiquiátrico/Neuro-psiquiátrico', 'Psiquiátrico/Neuro-psiquiátrico'), ('Geriátrico', 'Geriátrico'), ('Banco de Sangre', 'Banco de Sangre'), ('Ambulancias/Emergencias Médicas', 'Ambulancias/Emergencias Médicas'), ('Enfermería', 'Enfermería'), ('Hemodiálisis', 'Hemodiálisis'), ('Odontología', 'Odontología'), ('Oftalmología', 'Oftalmología'), ('Farmacia/Droguería', 'Farmacia/Droguería'), ('Veterinaria', 'Veterinaria'), ('Morgue', 'Morgue'), ('Neomatología', 'Neomatología'), ('Podología', 'Podología'), ('Hogar de Ancianos', 'Hogar de Ancianos'), ('Kinesiología', 'Kinesiología'), ('Otros', 'Otros')], max_length=400)),
                ('recoleccion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Domingo'), ('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], max_length=13, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('responsable_ambiental', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recorrido', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cp', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Provincia'),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Localidad'),
        ),
        migrations.AddField(
            model_name='baldeutilizado',
            name='establecimiento_generador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador'),
        ),
        migrations.AddField(
            model_name='baldeutilizado',
            name='hoja_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.HojaRuta'),
        ),
        migrations.AddField(
            model_name='balde',
            name='establecimiento_generador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador'),
        ),
    ]
