# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 22:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcopioTransitorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_interno_p_estacionar', models.BooleanField()),
                ('dimension_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('camara_frio', models.BooleanField()),
                ('dimension_camara_frio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbitoDependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Ministerio de Salud', 'Ministerio de Salud'), ('Municipal', 'Municipal'), ('Privado', 'Privado'), ('Otro', 'Otro')], max_length=50)),
                ('municipalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('centro_que_depende', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balde',
            fields=[
                ('nro_balde', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50'), ('120', '120'), ('240', '240')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BaldeUtilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_precinto', models.BigIntegerField()),
                ('tipo', models.CharField(choices=[('Entrega', 'Entrega'), ('Retiro', 'Retiro')], max_length=15)),
                ('balde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Balde')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_quirofanos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nro_camas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('poblacion_promedio_atendida', models.FloatField(default=0)),
                ('poblacion_promedio_atendida_365', models.FloatField(default=0)),
                ('via_acceso', multiselectfield.db.fields.MultiSelectField(choices=[('Asfalto', 'Asfalto'), ('Ripio', 'Ripio'), ('Tierra', 'Tierra'), ('Camino consolidado', 'Camino consolidado')], max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vinculo', models.DateField()),
                ('cuit_cuil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatoImpositivo',
            fields=[
                ('impuestos_ganancias', multiselectfield.db.fields.MultiSelectField(choices=[('Inscripto', 'Inscripto'), ('No Inscripto', 'No Inscripto'), ('Excento', 'Excento'), ('Agente de Retención', 'Agente de Retención')], max_length=50)),
                ('impuestos_valor_agregado', multiselectfield.db.fields.MultiSelectField(choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('Responsable Excento', 'Responsable Excento'), ('Consumidor Final', 'Consumidor Final'), ('Monotributista', 'Monotributista'), ('Agente de Retención', 'Agente de Retención')], max_length=93)),
                ('ingresos_brutos', multiselectfield.db.fields.MultiSelectField(choices=[('Contribuyente Directo', 'Contribuyente Directo'), ('Pasible de Retención/Percepción', 'Pasible de Retención/Percepción')], max_length=53)),
                ('nro_iibb', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('calle_entre1', models.CharField(blank=True, max_length=50, null=True)),
                ('calle_entre2', models.CharField(blank=True, max_length=50, null=True)),
                ('nro', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('piso', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dpto', models.CharField(blank=True, max_length=50, null=True)),
                ('comarca', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstablecimientoGenerador',
            fields=[
                ('nro_inscripcion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('fecha_vinculo', models.DateField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones_comentarios', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('tipo_actividad', multiselectfield.db.fields.MultiSelectField(choices=[('Hospital', 'Hospital'), ('Centro de Salud', 'Centro de Salud'), ('Clínica', 'Clínica'), ('Sanatorio', 'Sanatorio'), ('Tatuajes', 'Tatuajes'), ('Cirugia', 'Cirugia'), ('Centro Diagnóstico', 'Centro Diagnóstico'), ('Centro Vacunación', 'Centro Vacunación'), ('Consultorio Médico', 'Consultorio Médico'), ('Investigación', 'Investigación'), ('Maternidad', 'Maternidad'), ('Pediatría', 'Pediatría'), ('Laboratorio', 'Laboratorio'), ('Psiquiátrico/Neuro-psiquiátrico', 'Psiquiátrico/Neuro-psiquiátrico'), ('Geriátrico', 'Geriátrico'), ('Banco de Sangre', 'Banco de Sangre'), ('Ambulancias/Emergencias Médicas', 'Ambulancias/Emergencias Médicas'), ('Enfermería', 'Enfermería'), ('Hemodiálisis', 'Hemodiálisis'), ('Odontología', 'Odontología'), ('Oftalmología', 'Oftalmología'), ('Farmacia/Droguería', 'Farmacia/Droguería'), ('Veterinaria', 'Veterinaria'), ('Morgue', 'Morgue'), ('Neomatología', 'Neomatología'), ('Podología', 'Podología'), ('Otros', 'Otros')], max_length=369)),
                ('sector', models.IntegerField()),
                ('ambito_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.AmbitoDependencia')),
                ('caract_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.CaracteristicasGenerales')),
                ('director_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_responsable', to='modulo_I.Cliente')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recorrido', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('volumen_retirado', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('0', 'Domingo'), ('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], max_length=20)),
                ('hora_desde_m', models.TimeField(blank=True, null=True, verbose_name='Hora desde (Mañana)')),
                ('hora_hasta_m', models.TimeField(blank=True, null=True, verbose_name='Hora hasta (Mañana)')),
                ('hora_desde_t', models.TimeField(blank=True, null=True, verbose_name='Hora desde (Tarde)')),
                ('hora_hasta_t', models.TimeField(blank=True, null=True, verbose_name='Hora hasta (Tarde)')),
                ('horario_retiro', models.TimeField(blank=True, null=True, verbose_name='Horario Retiro')),
                ('establecimiento_generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ResiduoGenerador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Contaminantes no Patogénicos', 'Contaminantes no Patogénicos'), ('Contaminantes Patogénicos', 'Contaminantes Patogénicos'), ('Contaminantes Peligrosos', 'Contaminantes Peligrosos')], max_length=80)),
                ('volumen_mensual_estimado', models.FloatField(default=0)),
                ('kgs_mensual_estimado', models.FloatField(default=0)),
                ('establecimiento_generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador')),
            ],
        ),
        migrations.CreateModel(
            name='ViaAccesoSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', multiselectfield.db.fields.MultiSelectField(choices=[('Pasillo interno del centro asistencial', 'Pasillo interno del centro asistencial'), ('Pasillo externo/lateral', 'Pasillo externo/lateral'), ('Escalera', 'Escalera'), ('Ascensor', 'Ascensor'), ('Acceso para tránsito vehicular interno', 'Acceso para tránsito vehicular interno')], max_length=119)),
                ('acopio_transitorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.AcopioTransitorio')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Provincia'),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='responsable_residuos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_residuos', to='modulo_I.Persona'),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='responsable_suplente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_suplente', to='modulo_I.Persona'),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='responsable_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_tecnico', to='modulo_I.Persona'),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='via_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.ViaAccesoSector'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='modulo_I.Persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_comercial', to='modulo_I.Persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dato_impositivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.DatoImpositivo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio_legal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Domicilio'),
        ),
        migrations.AddField(
            model_name='baldeutilizado',
            name='hoja_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.HojaRuta'),
        ),
        migrations.AddField(
            model_name='balde',
            name='establecimiento_generador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador'),
        ),
        migrations.AlterUniqueTogether(
            name='residuogenerador',
            unique_together=set([('tipo', 'establecimiento_generador')]),
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together=set([('dia', 'establecimiento_generador')]),
        ),
        migrations.AlterUniqueTogether(
            name='balde',
            unique_together=set([('nro_balde', 'establecimiento_generador')]),
        ),
    ]
