# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehojaruta',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='detallehojaruta',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
