# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='recorrido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_I.Recorrido'),
        ),
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='recorrido_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrido_extra', to='modulo_I.Recorrido'),
        ),
    ]
