# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 22:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrante',
            name='nro_parada',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cuadrante',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Sector'),
        ),
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='tipo_actividad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ambulancias/Emergencias Médicas', 'Ambulancias/Emergencias Médicas'), ('Banco de Sangre', 'Banco de Sangre'), ('Centro Diagnóstico', 'Centro Diagnóstico'), ('Centro Vacunación', 'Centro Vacunación'), ('Centro de Salud', 'Centro de Salud'), ('Cirugia', 'Cirugia'), ('Clínica', 'Clínica'), ('Consultorio Médico', 'Consultorio Médico'), ('Enfermería', 'Enfermería'), ('Farmacia/Droguería', 'Farmacia/Droguería'), ('Geriátrico', 'Geriátrico'), ('Hemodiálisis', 'Hemodiálisis'), ('Hogar de Ancianos', 'Hogar de Ancianos'), ('Hospital', 'Hospital'), ('Investigación', 'Investigación'), ('Kinesiología', 'Kinesiología'), ('Laboratorio', 'Laboratorio'), ('Maternidad', 'Maternidad'), ('Morgue', 'Morgue'), ('Neomatología', 'Neomatología'), ('Odontología', 'Odontología'), ('Oftalmología', 'Oftalmología'), ('Otros', 'Otros'), ('Pediatría', 'Pediatría'), ('Podología', 'Podología'), ('Psiquiátrico/Neuro-psiquiátrico', 'Psiquiátrico/Neuro-psiquiátrico'), ('Sanatorio', 'Sanatorio'), ('Tatuajes', 'Tatuajes'), ('Veterinaria', 'Veterinaria')], max_length=400),
        ),
    ]
