# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
