# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehojaruta',
            name='hora_llegada',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='detallehojaruta',
            name='hora_salida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
