# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baldeutilizado',
            name='balde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Balde'),
        ),
    ]
