# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balde',
            name='capacidad',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50'), ('120', '120'), ('240', '240')], max_length=5),
        ),
    ]
