# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:29
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='tipo_actividad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ambulancias/Emergencias Médicas', 'Ambulancias/Emergencias Médicas'), ('Banco de Sangre', 'Banco de Sangre'), ('Centro Diagnóstico', 'Centro Diagnóstico'), ('Centro Vacunación', 'Centro Vacunación'), ('Centro de Salud', 'Centro de Salud'), ('Cirugia', 'Cirugia'), ('Clínica', 'Clínica'), ('Consultorio Médico', 'Consultorio Médico'), ('Enfermería', 'Enfermería'), ('Farmacia/Droguería', 'Farmacia/Droguería'), ('Geriátrico', 'Geriátrico'), ('Hemodiálisis', 'Hemodiálisis'), ('Hogar de Ancianos', 'Hogar de Ancianos'), ('Hospital', 'Hospital'), ('Investigación', 'Investigación'), ('Kinesiología', 'Kinesiología'), ('Laboratorio', 'Laboratorio'), ('Maternidad', 'Maternidad'), ('Morgue', 'Morgue'), ('Neomatología', 'Neomatología'), ('Odontología', 'Odontología'), ('Oftalmología', 'Oftalmología'), ('Otros', 'Otros'), ('Pediatría', 'Pediatría'), ('Podología', 'Podología'), ('Psiquiátrico/Neuro-psiquiátrico', 'Psiquiátrico/Neuro-psiquiátrico'), ('Sanatorio', 'Sanatorio'), ('Tatuajes', 'Tatuajes'), ('Veterinaria', 'Veterinaria')], max_length=400, null=True),
        ),
    ]
