# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrohojaruta',
            unique_together=set([('fecha_recorrido', 'establecimiento_generador')]),
        ),
    ]
