# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_remove_establecimientogenerador_hora_atención'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimientogenerador',
            old_name='dia_atención',
            new_name='dia_atencion',
        ),
    ]
