# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180122_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baldeutilizado',
            name='nro_entrega',
        ),
        migrations.RemoveField(
            model_name='baldeutilizado',
            name='nro_retiro',
        ),
        migrations.AddField(
            model_name='baldeutilizado',
            name='balde_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nro_retiro', to='modulo_I.Balde'),
        ),
    ]
