# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180222_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baldepactado',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
