# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180207_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='balde',
            name='establecimiento_generador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_I.EstablecimientoGenerador'),
        ),
        migrations.AlterField(
            model_name='balde',
            name='estado',
            field=models.CharField(choices=[('En Planta', 'En Planta'), ('Ocupado', 'Ocupado')], default='En Planta', max_length=15),
        ),
    ]
