# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180223_2131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuadrante',
            unique_together=set([('sector', 'nombre_cuadrante')]),
        ),
    ]
