# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180220_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='itinerario',
        ),
        migrations.DeleteModel(
            name='Itinerario',
        ),
    ]
