# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180225_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientogenerador',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_I.Localidad'),
        ),
    ]
