# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 00:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180201_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='cp',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
