# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0002_auto_20180212_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimientogenerador',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='establecimientogenerador',
            name='nro_inscripcion',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
