# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0003_auto_20180122_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baldeutilizado',
            name='balde_retiro',
        ),
    ]
