# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0003_auto_20180217_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('dia', models.CharField(choices=[('0', 'Domingo'), ('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='itinerario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_I.Itinerario'),
        ),
    ]
