# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0003_auto_20180222_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balde',
            name='nro_balde',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='baldepactado',
            unique_together=set([('establecimiento_generador', 'capacidad_balde', 'color_precinto')]),
        ),
    ]
