# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_I', '0003_auto_20180214_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
